version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile-nextjs
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POKEAPI_URL=https://pokeapi.co/api/v2

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
